-- Pricing data (seasons, rates, discount tiers, liberados tiers) is seeded
-- directly by supabase/migrations/0015_authoritative_spec_rebuild.sql, which
-- is the authoritative source (extracted from the real spreadsheet spec).
-- This file intentionally has no pricing inserts to avoid duplicating or
-- conflicting with that migration on `supabase db reset`.
